common_config:
  seed: 42
  num_workers: 4
  ddp: True
  save_vis: False
  load_ckpt: ckpts/model.step228000.pth
  reduce_memory: False #delete intermediate results and models to free memory
hydra:
  run: 
    dir: outputs/benchmark/ggpt_vggt-point-romav2-base

ggptmodel_config:
  _target_: ggpt.model.base.BasePredictor
  grid_resolution: 384 
  type_embed_dim: 16
  sinusoidal_dim: 32
  zero_init: True
  predict_residual: True
  backbone_type: 'ptv3' #or 'spconv_unet'
  ptv3_config:
    enc_dim: 128
    output_dim: 96
    turn_off_bn: False 
    stride: 
      - 2
      - 2
      - 2
      - 2
    enable_flash: True
    embedding_type: 'MLP'
  head_width: 256
  
valdataset_configs:
  _target_: ggpt.dataloader.eval_dataset.EvalDataset
  pca_transform: False
  chunk_sample: 'random'
  data_dict:
    4ddress_vggt-point-romav2-base: outputs/benchmark/sfm_vggt-point-romav2-base/save/4ddress/*