
valdataset_configs: 
  - _target_: sfm.dataloader.extracted.ExtractedDataset
    name: eth3d_4views
    root: GGPT_eval/ind_data/eth3d/4
    sample_extracted: True
  - _target_: sfm.dataloader.extracted.ExtractedDataset
    name: eth3d_8views
    root: GGPT_eval/ind_data/eth3d/8
    sample_extracted: True
  - _target_: sfm.dataloader.extracted.ExtractedDataset
    name: eth3d_16views
    root: GGPT_eval/ind_data/eth3d/16
    sample_extracted: True
  - _target_: sfm.dataloader.extracted.ExtractedDataset
    name: scannetpp_4views
    root: GGPT_eval/ind_data/scannetpp/4
    sample_extracted: True
  - _target_: sfm.dataloader.extracted.ExtractedDataset
    name: scannetpp_8views
    root: GGPT_eval/ind_data/scannetpp/8
    sample_extracted: True
  - _target_: sfm.dataloader.extracted.ExtractedDataset
    name: scannetpp_16views
    root: GGPT_eval/ind_data/scannetpp/16
    sample_extracted: True
  - _target_: sfm.dataloader.extracted.ExtractedDataset
    name: tandt_4views
    root: GGPT_eval/ind_data/tandt/4
    sample_extracted: True
  - _target_: sfm.dataloader.extracted.ExtractedDataset
    name: tandt_8views
    root: GGPT_eval/ind_data/tandt/8
    sample_extracted: True
  - _target_: sfm.dataloader.extracted.ExtractedDataset
    name: tandt_16views
    root: GGPT_eval/ind_data/tandt/16
    sample_extracted: True
  - _target_: sfm.dataloader.extracted.ExtractedDataset
    name: mvdvrk
    root: GGPT_eval/ood_data/mvdvrk
    sample_extracted: True
  - _target_: sfm.dataloader.extracted.ExtractedDataset
    name: 4ddress
    root: GGPT_eval/ood_data/4ddress
    sample_extracted: True



feedforward_config:
  model: vggt-point
  dav3:
    input_pose: False   
  pi3x:
    input_intrinsics: False
    input_extrinsics: False

match_config:
  models: ['romav2-base']
  save_vis: False

ba_config:
  score_thresh: 0.6
  cycle_err_thresh: 2
  ff_err_thresh: null
  mintrack_per_view: 2048
  shared_camera: True #!
  refine_focal_length: True
  calibrated: False  
  loss_function_type: 'cauchy'
  loss_function_scale: 0.1
  camera_type: PINHOLE

dlt_config:
  score_thresh: 0.1
  cycle_err_thresh: 4 
  max_epipolar_error: 4 # no
  min_tri_angle: 3
  max_reproj_error: 4
  batch_size: 500000

common_config:
  seed: 47
  ddp: True
  num_workers: 4
  save_vis: False
  save_outputs: True
  run_sfm: True
  reduce_memory: False #delete intermediate results and models to free memory

hydra:
  run: 
    dir: outputs/benchmark/vggt-point_romav2-base