"""Named API for pipeline orchestration; implementations live in owned modules."""

from ffba.geometry import (
    camera_centers_from_w2c,
    camera_viewing_axes_from_w2c,
    to_homogeneous_w2c,
    center_local_extrinsics,
    global_pose_dicts_from_w2c,
)
from ffba.matching.observations import (
    count_track_observations,
    remap_pairs,
    remap_prior_tracks,
    filter_low_coverage_frames,
    merge_keypoints_per_image,
    snap_prior_tracks_to_features,
    tracks_to_keypoints_and_matches,
)
from ffba.matching.projected_overlap import (
    _regular_grid_samples,
    _bilinear_sample_numpy,
    _depth_confidence_thresholds,
    _prepare_projected_overlap_source,
    _score_projected_overlap_pair,
    build_projected_overlap_groups,
)
from ffba.matching.scheduling import (
    select_sift_first_centers,
    simulate_sift_schedule_thresholds,
)
from ffba.matching.sift import (
    canonicalize_pair_array,
    build_temporal_pairs,
    build_sift_candidate_pairs,
    _grid_coverage_for_matched_keypoints,
    analyze_sift_schedule_graph,
)
from ffba.matching.vggsfm import (
    sample_query_points,
    apply_image_change,
    invert_image_change,
    prepare_vggsfm_tracker_images,
    build_vggsfm_query_points,
    precompute_vggsfm_tracker_fmaps,
    run_vggsfm_prior_tracks,
)
from ffba.matching.vggsfm_groups import (
    build_sift_pose_dino_candidate_details,
    build_three_layer_vggsfm_groups,
    summarize_groups,
    build_pose_groups,
    build_vggsfm_groups,
)
from ffba.reconstruction.budget import (
    _camera_centers_from_reconstruction,
    _track_max_triangulation_angle_degrees,
    _current_track_angular_error_p90,
    _summarize_track_records_by_source,
    _plan_bae_track_deletions,
    prune_reconstruction_for_bae_observation_budget,
)
from ffba.reconstruction.database import (
    average_intrinsics_with_gluemap,
    load_database_keypoint_features,
    load_database_keypoints_per_image,
    summarize_database_matches,
    prepare_sift_database_for_refine,
    _copy_colmap_camera,
    _read_database_descriptors,
    _write_database_descriptors,
    filter_sift_database_for_refine,
    _write_cameras_and_images,
    write_tracks_database,
    write_coarse_reconstruction,
)
from ffba.reconstruction.refinement import (
    _bae_huber_delta_for_iteration,
    run_merg3r_augmented_refinement_loop,
)
from ffba.reconstruction.tracks import (
    run_select_tracks,
    run_reprojection_filter_with_stats,
    triangulate_from_seed_reconstruction,
)
from ffba.reporting.statistics import (
    summarize_counts,
    format_count_summary,
    summarize_intrinsics,
    save_intrinsics_artifacts,
    summarize_numeric,
    summarize_distribution,
)
from ffba.reporting.tracks import (
    classify_point3d_track_source,
    build_s_keypoint_count,
    classify_tracks_by_s_keypoints,
    summarize_angular_errors_by_track_source,
    log_angular_errors_by_track_source,
    count_reconstruction_observations,
    summarize_reconstruction,
    summarize_ba_solver_result,
)
from ffba.runtime import (
    _lazy_import_pycolmap,
    _ensure_gluemap_imports,
    debug,
    suppress_native_stdio,
)
from ffba.reconstruction.budget import BAE_MIN_OBSERVATIONS_PER_IMAGE
from scipy.spatial import cKDTree

__all__ = [
    "camera_centers_from_w2c",
    "camera_viewing_axes_from_w2c",
    "to_homogeneous_w2c",
    "center_local_extrinsics",
    "global_pose_dicts_from_w2c",
    "count_track_observations",
    "remap_pairs",
    "remap_prior_tracks",
    "filter_low_coverage_frames",
    "merge_keypoints_per_image",
    "snap_prior_tracks_to_features",
    "tracks_to_keypoints_and_matches",
    "_regular_grid_samples",
    "_bilinear_sample_numpy",
    "_depth_confidence_thresholds",
    "_prepare_projected_overlap_source",
    "_score_projected_overlap_pair",
    "build_projected_overlap_groups",
    "select_sift_first_centers",
    "simulate_sift_schedule_thresholds",
    "canonicalize_pair_array",
    "build_temporal_pairs",
    "build_sift_candidate_pairs",
    "_grid_coverage_for_matched_keypoints",
    "analyze_sift_schedule_graph",
    "sample_query_points",
    "apply_image_change",
    "invert_image_change",
    "prepare_vggsfm_tracker_images",
    "build_vggsfm_query_points",
    "precompute_vggsfm_tracker_fmaps",
    "run_vggsfm_prior_tracks",
    "build_sift_pose_dino_candidate_details",
    "build_three_layer_vggsfm_groups",
    "summarize_groups",
    "build_pose_groups",
    "build_vggsfm_groups",
    "_camera_centers_from_reconstruction",
    "_track_max_triangulation_angle_degrees",
    "_current_track_angular_error_p90",
    "_summarize_track_records_by_source",
    "_plan_bae_track_deletions",
    "prune_reconstruction_for_bae_observation_budget",
    "average_intrinsics_with_gluemap",
    "load_database_keypoint_features",
    "load_database_keypoints_per_image",
    "summarize_database_matches",
    "prepare_sift_database_for_refine",
    "_copy_colmap_camera",
    "_read_database_descriptors",
    "_write_database_descriptors",
    "filter_sift_database_for_refine",
    "_write_cameras_and_images",
    "write_tracks_database",
    "write_coarse_reconstruction",
    "_bae_huber_delta_for_iteration",
    "run_merg3r_augmented_refinement_loop",
    "run_select_tracks",
    "run_reprojection_filter_with_stats",
    "triangulate_from_seed_reconstruction",
    "summarize_counts",
    "format_count_summary",
    "summarize_intrinsics",
    "save_intrinsics_artifacts",
    "summarize_numeric",
    "summarize_distribution",
    "classify_point3d_track_source",
    "build_s_keypoint_count",
    "classify_tracks_by_s_keypoints",
    "summarize_angular_errors_by_track_source",
    "log_angular_errors_by_track_source",
    "count_reconstruction_observations",
    "summarize_reconstruction",
    "summarize_ba_solver_result",
    "_lazy_import_pycolmap",
    "_ensure_gluemap_imports",
    "debug",
    "suppress_native_stdio",
    "BAE_MIN_OBSERVATIONS_PER_IMAGE",
    "cKDTree",
]
